### ISSUE TITLE
porter_lightweight demo在idea启动之后，页面加载不了

### ISSUE THREAD

**Issue by onemoreflag** [apache/servicecomb-samples#92]
porter_lightweight demo在idea启动之后，页面加载不了
![image](https://user-images.githubusercontent.com/48425509/159196477-a9f14db6-2cdd-475c-ab9a-36184c693af3.png)
报错信息：
[2022-03-21 10:00:38,760][transport-vert.x-eventloop-thread-8][ERROR][io.vertx.ext.web.RoutingContext:] Unhandled exception in router
java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.Http1xServerRequest.checkEnded(Http1xServerRequest.java:655) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerRequest.handler(Http1xServerRequest.java:293) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:103) ~[vertx-web-4.1.5.jar:4.1.5]
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler.handle(RestBodyHandler.java:111) ~[transport-rest-vertx-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler.handle(RestBodyHandler.java:56) ~[transport-rest-vertx-2.6.0.jar:2.6.0]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:203) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2022-03-21 10:00:38,775][transport-vert.x-eventloop-thread-8][ERROR][org.apache.servicecomb.samples.porter.gateway.StaticWebpageDispatcher:48] 
java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.Http1xServerRequest.checkEnded(Http1xServerRequest.java:655) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerRequest.handler(Http1xServerRequest.java:293) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:103) ~[vertx-web-4.1.5.jar:4.1.5]
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler.handle(RestBodyHandler.java:111) ~[transport-rest-vertx-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler.handle(RestBodyHandler.java:56) ~[transport-rest-vertx-2.6.0.jar:2.6.0]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:203) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by liubao68** [comment]
看看 ： https://github.com/apache/servicecomb-samples/issues/53
